---
title: "About the Benbow Lab"
output:
  html_document:
    toc: true
    toc_float: true
---

The National Microbiome Initiative provides a clear impetus that understanding the microbiome of humans and the environment has unique potential to influence scientific discovery and impact many aspects of the human condition. These impacts have been initially identified for areas of research such as chronic disease, food security, and ecosystem services; however, more intense mechanistic investigation is necessary for a deeper understanding of how the discoveries of the microbiome challenge traditional understanding and investigation in many other disciplines.

#Background and Approach
The research in my lab investigates the microbiome of humans, animals and the environment by taking innovative approaches for understanding the importance of entire microbial communities to human health, forensics and ecological systems. To accomplish these goals, we take a systems approach and collaborate with an interdisciplinary team of scientists with expertise ranging from pathogenic microbiology to agent-based mathematical modeling, chemical engineering, and behavior to take findings from basic, fundamental studies for answering innovative applied research questions. Our collaborative team and systems approach integrates expertise in a way that identifies mechanisms of how entire microbial assemblages can influence specific microbial taxa (or their genomes) and act as ‘signatures’ in forensic investigations, infectious disease responses, antimicrobial resistance profiles, and dictate ecological foodwebs and species networks.  We also identify the biological mechanisms that produce these signatures to inform future translation studies.
The Benbow Lab at MSU is seeking contact with researchers doing human decomposition studies in this USA or abroad.  We are particularly interested in potentially working with scientists with a mutual interest in insect-microbe interactions. For those interested please contact Dr. Eric Benbow (benbow@msu.edu).
