---
title: "Aquatic Ecosystems"
description: "Aquatic Entomology Project Focuses"
output:
    html_document:
      toc: true
      toc_float: true
---

Aquatic habitats contribute to ecosystem processes in every biome of Earth. In these systems there are notable bottom-up and top-down controls that often work synergistically to regulate ecosystem function and resilience to perturbations. Aquatic studies in the Benbow Lab are addressing mechanistic questions at several scales of inquiry. These studies range from top-down control of epiphytic biofilm development to collaborative efforts quantifying the role of hydraulic habitat templates on macroinvertebrate community assembly and the influence of native riparian plants on in-stream ecosystem processes. Additional studies are on-going in the Republic of Palau in understanding the factors that influence the resilience or change of watersheds to land use degradation and developing unique bioassessment methods to monitor such ecosystem responses.

#Invasive Plant Impacts on Riparian-Aquatic Linkages
Exotic species have detrimental impacts on native ecosystems and cost human society nearly $137 billion per year.  Non-native invasive plants tend to degrade habitats by out competing native plants and reducing biodiversity within ecosystems.  Plant invaders are most successful in disturbed habitats such as flood plains and habitat edges.  Riparian zones (forested regions along stream banks) are regularly disturbed habitats, and therefore, easily invaded by invasive plants.  Due to this characteristic, riparian zones provide an area where invasive plants interact and impact aquatic systems.  Understanding how invasive riparian plants influence connections between terrestrial and aquatic habitats is the overarching goal in this research project. Aquatic systems depend on inputs from terrestrial environments (e.g. leaves, woody debris, and other detrital materials) to support aquatic food-webs and ecosystem processes.  Macroinvertebrate and microbial communities use terrestrial inputs for habitat and food resources.  Therefore, changes in leaf litter inputs from the terrestrial environment due to the introduction of a terrestrial invasive plant may result in substantial impacts on aquatic communities and food-web dynamics.  Changes in terrestrial leaf inputs may further influence stream organic matter processing, nutrient cycling, and light availability within streams. Amur honeysuckle (Lonicera maackii: a type of bush honeysuckle) is an invasive species that has rapidly become dominant in the forested areas of the Midwestern and eastern USA.  Once this species is established it 1) reduces the growth and reproductive success of native shrubs and trees, 2) negatively impacts the growth and survivorship of terrestrial insects, and 3) is responsible for the loss of native plant diversity through competition.  Quasi-monocultures of Amur honeysuckle have been found in riparian zones throughout the Miami Valley, OH region and create dense shrub canopies overarching streams.  These honeysuckle canopies contribute a substantial amount of leaf litter that enter streams, providing an excellent model system to identify the impacts riparian invasive plants have on aquatic food-webs and ecosystem processes. Our research objectives are 1) to identify the impacts of Amur honeysuckle on terrestrial-aquatic connections through examination of cross-system subsidies, food-web dynamics, and ecosystem processes and 2) to determine the potential toxicity effects of Amur honeysuckle on aquatic macroinvertebrates.  We are conducting a series of field and laboratory experiments to gain a pattern to process understanding of the impacts Amur honeysuckle has on aquatic systems.  We hope that our research findings will support local and regional restoration and management programs while broadening our understanding of how invasive species influence ecosystem dynamics.

#Other Projects
